#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App4.Resource", IsApplication=true)]

namespace App4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int button1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button2 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int buttonA1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int buttonA2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int buttonA3 = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int buttonM1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int buttonM2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int buttonM3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int buttonM4 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int buttonM5 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int buttonM6 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int buttonM7 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int buttonM8 = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textView3 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AutoActivity = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ManualActivity = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int Addit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int econom = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ict = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ivt = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int logist = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int manager = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int naladshik = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int pks = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int secretarsh = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Test = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int yorist = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int yp = 2130903051;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
